# Site settings
title: Hongru Hou
description: > # this means to ignore newlines until "baseurl:"
  Hongru Hou is an interaction designer and an ex-front-end engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hongru.hou.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
